### ISSUE TITLE
Blog Post:  admiral mini posts 

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#113]
### Blog Post

A short list of candidates to showcase on blog from admiral

- [ ] [derive_var_obs_number()](https://pharmaverse.github.io/admiral/reference/derive_var_obs_number.html)
- [ ] https://pharmaverse.github.io/admiral/reference/use_ad_template.html
- [ ] https://pharmaverse.github.io/admiral/reference/derive_summary_records.html
- [ ] https://pharmaverse.github.io/admiral/reference/derive_vars_period.html
- [ ] https://pharmaverse.github.io/admiral/reference/derive_vars_computed.html
- [ ] https://pharmaverse.github.io/admiral/reference/derive_vars_extreme_event.html
- [ ] https://pharmaverse.github.io/admiral/reference/derive_locf_records.html

@manciniedoardo and @StefanThoma these are potential admiral functions to cover in the future.

**Comment by bms63** [comment]
Also @pharmaverse/admiral_comm if anyone wants to write a brief post on how to use any of the above functions it would be much appreciated!!  

Or if you got other ideas for blog posts then lets go!!

**Comment by manciniedoardo** [comment]
I would like to write a blog post next week on some of the `filter` functions (`filter_extreme()` etc. @pharmaverse/admiral_comm  what do you think?

**Comment by bms63** [comment]
Sounds awesome to me!!
