### ISSUE TITLE
Blog Post:  Dealing with Encoding Issues in R

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#114]
### Blog Post

@StefanThoma you had mentioned discussing encoding issues in our last meeting.  Just putting a placeholder here for you.

**Comment by bms63** [comment]
@StefanThoma any interest in writing this one - if lets close?

**Comment by StefanThoma** [comment]
Maybe later, once I have a bit more time on my hands. 
Closed it for now, thanks for keeping your eye on it.
