### ISSUE TITLE
General Issue: Experimenting with Docker Image for Contributor

### ISSUE THREAD

**Issue by donyunardi** [pharmaverse/blog#118]
### Background Information
Currently, when users want to contribute or create a post in the repository, they must install all R package dependencies that the repository requires before the contributor blog page can be rendered.

Related issue: https://github.com/pharmaverse/blog/issues/108

This could hinder the user's ability to move quickly and may potentially pollute their local environment. Users should be able to contribute to the repository without having to install all dependencies.

### Proposal
My proposal is to create a Docker image with all the dependencies installed and push this to the registry. 
Users can pull and use the image for development before pushing commits to the repository.

**Comment by donyunardi** [comment]
### Plan
* use `rocker/rstudio` as a base for users
* install quarto
* install R package dependencies

**Comment by donyunardi** [comment]
@bms63 

I pushed a registry to pharmaverse but don't have access to link it to the `blog` repo.
![image](https://github.com/pharmaverse/blog/assets/8597300/1d22740d-0108-4574-8898-08e59f3baf92)

Can you do this?

**Comment by bms63** [comment]
I clicked some buttons! https://github.com/pharmaverse/blog/pkgs/container/blog

let me know if it worked.

**Comment by donyunardi** [comment]
It works!
![image](https://github.com/pharmaverse/blog/assets/8597300/0477b408-8ca7-4731-87c5-4943d2455690)

Alright, two more things on my to-do list and then we can write a blog and have people try this to get feedback.
👍🏼
