### ISSUE TITLE
Bug: PR is failing CICD check

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/blog#127]
### What happened?

PR failing CICD check with the following error message
![image](https://github.com/pharmaverse/blog/assets/112789549/6dcc962e-4802-4e35-9168-05c38e0234ab)

Additional info from the check
![image](https://github.com/pharmaverse/blog/assets/112789549/7bd7d6be-7c8b-4070-9fb4-826872ecc097)

![image](https://github.com/pharmaverse/blog/assets/112789549/9dd29909-f9ab-4d62-9396-f7638f9a70c4)

**Comment by bms63** [comment]
No longer an issue
