### ISSUE TITLE
Disclaimer: Insert into all and future posts

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#133]
I saw this Disclaimer in a recent post - might be good to insert into other posts:

 https://github.com/pharmaverse/blog/pull/131/files#

![image](https://github.com/pharmaverse/blog/assets/10111024/a493a85d-271f-43d9-b795-d085343bbc30)

**Comment by bms63** [comment]
@pharmaverse/commswg wdyt?

**Comment by StefanThoma** [comment]
Seems appropriate, certainly for the Pharma companies involved. 
I think it would be good to add it to the template and if it does not apply the author can remove it.

**Comment by sadchla-codes** [comment]
This is definitely a great idea!

**Comment by manciniedoardo** [comment]
Agree to include moving forward.
