### ISSUE TITLE
admiral website highlights

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/blog#14]
What's on the website/brief tour

- [ ] Version on website and what they mean?
- [ ] templates versus vignettes
- [ ] families and keywords
- [ ] function documentation strategy
- [ ] ?

**Comment by sadchla-codes** [comment]
> Hi @sadchla-codes were you going to work on this blog post?

Yes @bms63, I can work on it

**Comment by bms63** [comment]
https://pharmaverse.github.io/admiraldiscovery/

I'm not sure @sadchla-codes is going to do this anymore.  I will un-assign and take on as I think it would be quick and nice post.

**Comment by sadchla-codes** [comment]
My apologies, I have completely forgot about this post. Thank you @bms63
