### ISSUE TITLE
Blog Post:  How fast is it to make a teal app?

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/blog#140]
### Blog Post

Vague idea:

Teal makes it fast and easy to make simple RShiny Apps. But how fast, and how easy? How little code do we need to make a working teal app (e.g. with a demog table and ae table) which we can then customise with our study data)? 

The example code could use `{phamraverseadam}` data.

@khatril are you or others in your team interested in this?

**Comment by bms63** [comment]
Seeing on the progress of this post?  We love to get it out soon!

**Comment by khatril** [comment]
Removing my assignment as I don't have bandwidth, please re-share with community to contribute to this great post!

**Comment by gigikenneth** [comment]
Hi! Happy to take on this blog post.

**Comment by manciniedoardo** [comment]
@gigikenneth I think someone in the tea; channel expressed interest as well when i posted about this there yesterday? Maybe you could connect and cooperate?

**Comment by gigikenneth** [comment]
@manciniedoardo Awesome, that would be great. I'll reach out to them.

**Comment by drorberel** [comment]
Will be glad to collaborate on this with @gigikenneth
