### ISSUE TITLE
Blog Post:  My experience as a new {admiral} developer

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/blog#142]
### Blog Post

@Fanny-Gautier @Lina2689 - do you think one (or both) of you could write a short and sweet post on the topic in the title? It'd be interesting to broadcast your experiences coming from a CRO and contributing to this open source package.

Possible topics:

- what experience you had when you started
- how you upskilled
- what have been the challenges/learnings
- what have you enjoyed

**Comment by manciniedoardo** [comment]
@akarpov0 tagging you in as well as an FYI but I know you have been busy with other projects recently.

**Comment by Fanny-Gautier** [comment]
Which tag should be selected for this topic ("Community", "Conferences") ? thanks

**Comment by manciniedoardo** [comment]
Hmm. Maybe community and adam?

**Comment by Fanny-Gautier** [comment]
The article is still ongoing and under upper management's review from our end.

**Comment by bms63** [comment]
Awesome - it will be great to have you and Cytel up on the pharmaverse blog!!

**Comment by manciniedoardo** [comment]
Looking forward to seeing it! When ready please feel free to make a PR and tag myself and @bms63 as reviewers 😄

**Comment by Fanny-Gautier** [comment]
Still under review for approval.. I have sent a gentle reminder yesterday. it's coming soon !
