### ISSUE TITLE
General Issue: Let people know about the newsletter

### ISSUE THREAD

**Issue by StefanThoma** [pharmaverse/blog#146]
### Background Information

Sign up here: 
https://forms.office.com/e/AJu4xWEGJx

Where do we publicize?

- LinkedIn (@bms63 will make a post)
- Spread within our company via group-chat
- admiral community meeting
- Spreading on the slack channels
- Anytime we make a post in slack channel
- Maybe add it to the template blog post to ask people whether they want to sign up?

**Comment by bms63** [comment]
We should ask folks presenting on admiral or other pharmaverse packages to give the blog mailing list a shout out.
