### ISSUE TITLE
Blog Post:  New pharmaverse council members announcement

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/blog#151]
### Blog Post

Won't spoil the surprise by naming them here, but @NNaikp will be preparing this and then i'll update the website after the news is shared.

**Comment by bms63** [comment]
![image](https://github.com/pharmaverse/blog/assets/10111024/b86babb0-07b5-45c1-92c5-8442ee5596c5)

**Comment by rossfarrugia** [comment]
@NNaikp think some of the images went a bit wrong when rendering if you get chance to take a look:

![image](https://github.com/pharmaverse/blog/assets/82581364/ad706bcf-dcc4-43b9-a769-a435ba4347f3)

![image](https://github.com/pharmaverse/blog/assets/82581364/4abc6e91-8503-4924-8fa9-9751655378a5)
