### ISSUE TITLE
Bug: Council update blogpost TOC looks strange

### ISSUE THREAD

**Issue by StefanThoma** [pharmaverse/blog#154]
### What happened?

<img width="1497" alt="Screenshot 2024-04-29 at 15 24 42" src="https://github.com/pharmaverse/blog/assets/40463122/34cd5a27-ac45-42da-9e26-8285399c8361">

**Comment by StefanThoma** [comment]
Also, typo in the title (I think)

**Comment by StefanThoma** [comment]
@bms63

**Comment by StefanThoma** [comment]
The preview image also does not work

<img width="934" alt="Screenshot 2024-04-29 at 15 40 37" src="https://github.com/pharmaverse/blog/assets/40463122/fb3a86e3-9c0d-4cb0-b5d5-bdb89aac3f69">

**Comment by NNaikp** [comment]
> Also, typo in the title (I think)

@StefanThoma Can you specify where you think it is? I can't see it 🙈 

Also, lesson learned for me: Never push something into production and then leave office 😅

**Comment by StefanThoma** [comment]
I should have been more specific; I think it should read: 
Appsilon and Sanofi join the pharmaverse council! 

(So no "s" after "join" because the subject joining is not singular)


No worries at all, could have been spotted in the review ;)

**Comment by NNaikp** [comment]
Will fix it 👍
