### ISSUE TITLE
Blog Post:  admiral future package extensions

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/blog#156]
### Blog Post

Someone from the admiralpeds team will write a small blog notifying of the plans for a summer first release of admiralpeds with a short explanation of the scope and companies involved (recognising Cytel as the first CRO to become official admiral co-developers of one of our packages), and also a note on our next plans for admiralobesity towards end of the year - with Novo Nordisk joining the collaboration.

**Comment by Fanny-Gautier** [comment]
Being not aware about admiralobesity, could you please give more details or let me know where I could find the information? Thank you

**Comment by rossfarrugia** [comment]
thanks @Fanny-Gautier! its still early days in planning for this one but here's a sentence that could be added to the bottom of your post:

_We also are excited to announce that some very early preparations have started on the next package extension joining our family - which will be a collaboration between Roche and Novo Nordisk (any maybe others) focused initially on endpoints in clinical trials for obesity. Name still to be decided - possibly {admiralmetabolic} - watch this space for more news!_

@manciniedoardo @bms63  - is that OK for you?

**Comment by bms63** [comment]
@rossfarrugia looks good to me!

**Comment by Fanny-Gautier** [comment]
Could you please suggest how to test the article ? While trying with "render" I get the following message:
![image](https://github.com/pharmaverse/blog/assets/157114584/8434765c-187b-470b-a3de-6a34f070afce)
and I haven't been able to install GLIBC_2.18.

I also raised a ticket to our IT in order to get Docker Image installed... but it's taking ages and I think that it will takes a few more days.

Thank you

**Comment by rossfarrugia** [comment]
@Fanny-Gautier feel free to make a PR and tag me as reviewer and i'd be happy to double check if easier. Another option could be if you wanted to set up a Posit Cloud account and use a workspace there.

**Comment by Fanny-Gautier** [comment]
Hi @bms63 , @rossfarrugia ,

Lina and I proceeded with the test on Posit and it now looks good. We are only having this below text appearing at the bottom of our article:
![image](https://github.com/pharmaverse/blog/assets/157114584/a3f3cd5e-dde4-444a-8167-cf787a85746e)
Not sure why and how we can get rid of it ?

Also while clicking "render" we realized that last updated date for all articles is now as Today's date. Is it expected ?
![image](https://github.com/pharmaverse/blog/assets/157114584/3f018db2-5351-4c70-be61-517d3bf3a8ec)

**Comment by bms63** [comment]
I believe this was fixed here - https://github.com/pharmaverse/blog/issues/169
