### ISSUE TITLE
Blog Post: Unix versus SAS time origin

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#180]
### Blog Post

In discussion in R Consortium Submission WG there was a finding around SAS versus Unix time.  Link and recording to come later

The CDISC Pilot Data update in Phuse Test Data Factory was using R unix time and gave +10 years to the dates. 😨 

The Pilot 3 re-derived ADaM data used xportr to help deal with this situation

![image](https://github.com/pharmaverse/blog/assets/10111024/33555bd1-65b8-4acd-9b75-2acf775f4fe7)

A post should be written about this issue.  

More to come.

**Comment by bms63** [comment]
Hey @cpiraux any interest on a short post on times in R and SAS and what to be careful of!?!

**Comment by cpiraux** [comment]
Yes, I might be interested in writing a short post on times in R and SAS.

**Comment by bms63** [comment]
@cpiraux yay!!  let me know if you want any help or how to use quarto blog stuff

**Comment by bms63** [comment]
Hi Celine!!  Hoping this is still on your radar!! @cpiraux
