### ISSUE TITLE
Enforce link package for {xyz}

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#181]
Provide guidance in PR Template on how to use the link package in blog post.

**Comment by manciniedoardo** [comment]
I wonder if we could enforce this through a CICD check?

**Comment by bms63** [comment]
It seems possible just not sure if it is worth the time to set up?

**Comment by manciniedoardo** [comment]
Hmm yeah. Maybe we could instead just add a checklist item.

**Comment by bms63** [comment]
haha - sorry to be the buzzkill.
