### ISSUE TITLE
General Issue: "falcon" will be renamed as "cardinal"

### ISSUE THREAD

**Issue by cicdguy** [pharmaverse/blog#189]
### Background Information

The "falcon" repo has already been renamed as "cardinal". Following the merge of https://github.com/pharmaverse/cardinal/pull/223, the name change will be 💯 complete.

Please update all references of "falcon" to "cardinal".

**Comment by rossfarrugia** [comment]
thanks Dinakar! i created https://github.com/pharmaverse/pharmaverse/issues/299 to make all the updates on website for this. will do that soon.

**Comment by manciniedoardo** [comment]
@telepath37 would you be able to tackle this or reassign? thanks

**Comment by StefanThoma** [comment]
@telepath37 
Is it possible to get this done by the end of the month?
