### ISSUE TITLE
Bug: https://pharmaverse.org/ is down

### ISSUE THREAD

**Issue by ran-codes** [pharmaverse/blog#191]
### What happened?

![image](https://github.com/pharmaverse/blog/assets/45013044/27d5c213-0c27-4ce1-b298-9fbf6c6091a4)

**Comment by bms63** [comment]
Thanks for the report @ran-codes !!

I am able to view it at this time in the screen shot 
![image](https://github.com/pharmaverse/blog/assets/10111024/cbe79fa7-4d52-484b-b7af-cd4833f45007)

**Comment by ran-codes** [comment]
**I just checked, and https://pharmaverse.org/ is now working.** 

Re unviewable images It may be a Github issue, as I can't see my profile picture anymore. Also I am checking some of my own github pages and they have the same connection error as I saw originally. So it seems to me that this is a GitHub issue that will resolve itself.

Thanks!!
