### ISSUE TITLE
Blog Post:  Introducing the aNCA package for Pharmaverse!

### ISSUE THREAD

**Issue by js3110** [pharmaverse/blog#233]
### Blog Post

I want to make a post to introduce the new aNCA pharmaverse package in development.

**Comment by rossfarrugia** [comment]
Package is now on pharmaverse site here as FYI: https://pharmaverse.org/e2eclinical/sdtm/

**Comment by manciniedoardo** [comment]
@js3110 could we get this out within November?

**Comment by js3110** [comment]
@manciniedoardo yes that is fine! I tried making a post in September but I didn't have access to push it to the repo at the time. Not sure if I do now

**Comment by manciniedoardo** [comment]
@js3110 you should do now

**Comment by js3110** [comment]
hi @manciniedoardo I am having trouble pushing or pulling to origin, and I tried to start from scratch and clone the repository but that also didn't work, same for my coworker. Are you aware of this issue?

**Comment by manciniedoardo** [comment]
![image](https://github.com/user-attachments/assets/e0702e5e-0223-4d57-89c2-ad11285cda44)

You have write access to the repo. What message are you getting? And what's your colleague's username? They may not have access.

**Comment by js3110** [comment]
the issue is with pushing, pulling and also I am unable to clone

i get this message if I try to clone the repo from github:
Cloning into 'C:\Users\spinnerj\Documents\GitHub\blog'...
remote: Enumerating objects: 9780, done.        
remote: Counting objects: 100% (3356/3356), done.        
remote: Compressing objects: 100% (1088/1088), done.        
remote: Total 9780 (delta 2602), reused 2773 (delta 2224), pack-reused 6424 (from 1)        
Receiving objects: 100% (9780/9780), 92.75 MiB | 11.90 MiB/s, done.
Resolving deltas: 100% (6434/6434), done.
error: invalid path 'posts/2024-01-04_end_of__year__up.../appendix.R'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

the colleague is @Gero1999 who should also have access since he is part of pharmaverse and aNCA. He is also unable to clone

**Comment by js3110** [comment]
@manciniedoardo  if i try to pull I get the following:
<img width="433" alt="image" src="https://github.com/user-attachments/assets/f13cd855-7d5f-4c61-812d-2a753c5c18ca">

**Comment by manciniedoardo** [comment]
Could I have your colleague's username pls? blog access is separate to pharmaverse access

**Comment by js3110** [comment]
its @Gero1999

**Comment by manciniedoardo** [comment]
@Gero1999 I added you as a collaborator too - pls check if anything changes and check your email to see if there is anything you need to accept - otherwise we can try debug

**Comment by js3110** [comment]
@manciniedoardo do you have any idea what is causing my issues when I try to pull?

**Comment by manciniedoardo** [comment]
@js3110 not immediately. upon looking at your error message carefully i actually don't think it's an access issue. Quick google gives [this](https://stackoverflow.com/questions/75673699/how-to-fix-the-problem-merge-with-strategy-ort-failed), have you tried that?

**Comment by js3110** [comment]
> @js3110 not immediately. upon looking at your error message carefully i actually don't think it's an access issue. Quick google gives [this](https://stackoverflow.com/questions/75673699/how-to-fix-the-problem-merge-with-strategy-ort-failed), have you tried that?

yes I tried but it doesn't work. I am also unable to checkout to main even though I have no unstaged changes or uncommitted changes.

**Comment by bms63** [comment]
This happened to me a few weeks ago.  I am wondering if the github action that modifies the timestamp is causing some issue with the git tree.  Might want to check with Dinakar

**Comment by js3110** [comment]
> This happened to me a few weeks ago. I am wondering if the github action that modifies the timestamp is causing some issue with the git tree. Might want to check with Dinakar

were you able to fix the issue?

**Comment by bms63** [comment]
> > This happened to me a few weeks ago. I am wondering if the github action that modifies the timestamp is causing some issue with the git tree. Might want to check with Dinakar
> 
> were you able to fix the issue?

I did, but I unfortunately don't remember what I did to fix it.  

I was just able to successfully do a fresh install from the main branch with no issues using Posit Cloud and

`R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.1 tools_4.4.1   `

**Comment by manciniedoardo** [comment]
@cicdguy any idea what might be broken here? thanks

**Comment by Gero1999** [comment]
Hey just to contribute to the topic! Maybe for now you can try to fork it and make the changes there? @js3110

**Comment by js3110** [comment]
> Hey just to contribute to the topic! Maybe for now you can try to fork it and make the changes there? @js3110

thanks @Gero1999 , but I dont think this will help as'I don't need to make any changes, I need to push my changes but if i try to push it tells me my branch is behind and i need to pull, which then gives me all the error messages :(

**Comment by manciniedoardo** [comment]
@js3110 any luck?

**Comment by js3110** [comment]
@manciniedoardo @cicdguy sorry, only just had a chance to try. Still no luck :/ when I run the git config code it does nothing and I still get the same errors when i try to pull.
