### ISSUE TITLE
Blog Post:  Working Groups in admiral

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#242]
### Blog Post

Discuss:
* Argument Aligning
* Date/Time Rework
* Lab Working Grou
* IG Review
* Environment handling
* Blogging!
* ?

**Comment by bms63** [comment]
I think this was closed in error @federicobaratin

**Comment by federicobaratin** [comment]
Hi @bms63!
Could you please provide more info on it? I have not understood well what happened

**Comment by bms63** [comment]
oh i am sorry @federicobaratin - I meant @manciniedoardo.  For some reason I confuse you both in my brain when doing @

**Comment by manciniedoardo** [comment]
Yeah looks like the wrong issue was mentioned in the PR - sorry for not spotting!
