### ISSUE TITLE
How to link function documentation to package documentation in blog posts

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#29]

**Comment by StefanThoma** [comment]
So for now quarto allows `code-link` only for code within chunks, not throughout the text. 
We can still manually link to the documentation, but that seems rather tedious. What do you @pharmaverse/tech-wg think?

Manual would be: 

`[function()](www.function.com)` rendered as: [function()](www.function.com)

**Comment by bms63** [comment]
Umm...I think we should risk and link the functions to the package source documentation.  Can someone set up the link check in #24 ?  This way we at least keep an eye on all our links until we get a permanent solution in place.

**Comment by StefanThoma** [comment]
Will do!
