### ISSUE TITLE
Blog Post: Newcomers and using admiral and collaboration cross company

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#37]
Newcomers and using admiral and collaboration cross company

**Comment by StefanThoma** [comment]
@pharmaverse/commswg looks like the post .qmd files don't need to be called `index`.
I propose to have somewhat relevant names. 
Keep in mind that this name will show in the URL.

**Comment by bms63** [comment]
That is good news - we should also figure out a standard convention for naming the post folder
