### ISSUE TITLE
change repo name

### ISSUE THREAD

**Issue by StefanThoma** [pharmaverse/blog#48]
Discussion point: 

I would like to change the name of the repo to better represent what we do here.
This is relevant because the name is featured in all URL's. 

github.com/pharmaverse/blog/ would not be bad. 
However, that somewhat depends on the scope: is it going to be *THE* pharmaverse blog? 
What about the thing NEST is planning?

What do *you* think, @pharmaverse/commswg

**Comment by bms63** [comment]
I'm not sure what NEST is planning, but I was assuming it was NEST focus.  I was thinking this blog could be admiral, xportr, logrx, envsetup and anything else related to Clinical Reporting.  

what about crblog so github.com/pharmaverse/crblog/

**Comment by StefanThoma** [comment]
For sure! 
I would probably still favour just `pharmaverse/blog`, as we also welcome NEST content, etc. even if we don't focus on that. 
Would you be good with that?

**Comment by bms63** [comment]
sure sounds good

**Comment by bms63** [comment]
We are now the blog
