### ISSUE TITLE
pharmaverse story in blog

### ISSUE THREAD

**Issue by nicholaswe** [pharmaverse/blog#66]
I was thinking of writing a post about what is pharmaverse, why we should choose it, where we can find its packages, and list some useful links.
Most of those information came from Ross Farrugia presentation on R/Pharma 2022 and were the base of the slides that were shared with the Council.

**Comment by bms63** [comment]
love that idea - be nice to get that into the blog site for those coming from linkedin.  

should be short as we don't want to re-create already existing documents - just link out to them like you said.

**Comment by nicholaswe** [comment]
Thanks for the advice, will work on that!
