### ISSUE TITLE
admiral story in blog

### ISSUE THREAD

**Issue by nicholaswe** [pharmaverse/blog#67]
I was thinking of writing a post about what is admiral, its birth (with screenshots), how was and how is the situation in terms of contributors, its extensions, and what is the modularized framework.
Most of those information came from Ross Farrugia presentation on R/Pharma 2022 and were the base of the slides that were shared with the Council.

**Comment by bms63** [comment]
There might be some overlap with a post that @StefanThoma is writing.  He is on vacation, but we can discuss!

**Comment by StefanThoma** [comment]
Hi @nicholaswe 
Sounds like a good post. 
I have recently done a presentation on my perspective on admiral with a focus on cross industry collaboration.
Here is the slide deck: https://stefanthoma.github.io/useR_2023_admiral/#/title-slide

If you think there is a lot of overlap between the two posts, based on my slides, please let me know. 
I would not mind if you want to take over this topic.

**Comment by nicholaswe** [comment]
Hello, @StefanThoma!

Very nice presentation, I liked your perspective on cross-industry collaboration :)

I wouldn't say we have a lot of overlap between our posts, but we talk about some similar things with different approaches. 
From what I got, your content is for a more technical and corporative audience, mine is for (future) R users.

I think it should be fine to have both posts, because you are emphasizing the advantages of adopting an open-source tool and these can be the "motivation" part for what I intend to present, a more practical and exampled content. 
Also, it would be nice to refer your post to mine, in this way, we can create a chain of admiral contents.

Please, let me know what you and @bms63 think.

Thanks!

**Comment by StefanThoma** [comment]
Yeah sounds good! 
Happy to chain the posts together, let me know when you have a link available.

Thanks!

**Comment by StefanThoma** [comment]
Hi @nicholaswe 
I have finished writing the blog post. 
When will yours be done?
You can check it out here: 
https://github.com/pharmaverse/blog/blob/37_cross_company_development/posts/2023-07-20_cross_company_dev/cross_industry_dev.qmd

Unless you upload your post before the review is done, I will not yet link to your post. 
Please let me know by when you plan to write the post.

**Comment by nicholaswe** [comment]
Hello, @StefanThoma!
Your post is very interesting and explanatory :) Good job!
I saw commented out the part where you link to mine, but I didn't start writing it yet because I'm working on another about pharmaverse.

I don't want to delay the publication of what is ready, so I think we can invert the order and I can point to your post by saying "...  the reasons why open-source is a more advantageous approach can be found in this post written by Stefan...".
What do you think?

Thanks and sorry about that.
