### ISSUE TITLE
Blog Post:  pharmaversesdtm is now out!

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/blog#90]
### Blog Post

Relationship with admiral.test and new features

**Comment by bms63** [comment]
Will you be making this post @kaz462?

**Comment by kaz462** [comment]
yes, will do next week :)

**Comment by bms63** [comment]
Hey all - did you all still want to post on these packages?  I think it would be very handy.  Post can be short!! :)

**Comment by manciniedoardo** [comment]
@kaz462 I leave it to you to decide - we have announced this in various so I am fine either way.

**Comment by bms63** [comment]
if it be a "no" @kaz462, then please close the issue.

...but I do think it is worthwhile to have a short post on the data packages!!!

**Comment by kaz462** [comment]
@bms63 Apologies for leaving this issue hanging for a while. I will close it as @manciniedoardo mentioned we have announced the release of two data packages, let's do it for the next release when we work more closely with the NEST team
