### ISSUE TITLE
Blog Post:  Encountering Floating Point in admiral

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#91]
### Blog Post

Summarize discussion on Floating point issues that occurred in this Pull Request.  The different solutions proposed should be discussed with pros/cons and why we made the decision we made in admiral.

https://github.com/pharmaverse/admiral/pull/2060

Can get in the technical weeds as I think it is a very interesting topic.

**Comment by StefanThoma** [comment]
I was thinking of adding a link to an excelent paper on this in SAS by Nigel Montgomery: 
https://phuse.s3.eu-central-1.amazonaws.com/Archive/2008/Connect/EU/Manchester/PAP_CS08.pdf

I think it would be a great reminder that such issues have always been around and is a recurring theme in stats programming. What do you think @bms63 ?

**Comment by bms63** [comment]
Feel free to add it in - maybe a summary of links at the end of the post would be handy?
